language: swift
osx_image: xcode12.3
env:
  global:
  - secure: d62d2f6Eadh3tkQ/OcIKTVPHHNqKXvG/DRYBSKq9koZ0UGJCkQN+DQGSvihEVAFkDIBYdDgdXtWB1pygi77SadjTaqCcM0J9u+NdZ1hroO3wk6MeILIO9KVmJSY5qQ/2vzoNqbgnR4jRRJQDGMBseiVwCGFbt9EavrEZkGOYFk8PKQmoJZssh96t+8T9CvOwJzRwu/sGm546AsjrhjO/4poyeyRtW6iABlCPay0sPCQJtCW/ayDQfkNtl4UWYVdjKjko/0h4o2tttCNnS+RvHCCMIDtb1MtAeyw4lugtJOI9VtLwvz5LFP06p+7XQ5Pehhhc+R9qOa4w9PKxPdP9BgnezUVBt+hC2nBWOzKuIVNiyyfPLBpLQmVid7pLMXxnYr8dPDLOwB+2EpqVMx49rPAopUMkkgdgC2LLdqH2XJRLpY+KDkSJC0hyJXvJyIK8460E3AEP81V7LGiyL+oIIv+4yHonLatcZdr05kd3dFIxeCXbyk3KHfEDNthWhSg56kcuZp2mok/FZE151VfGARo5HM5NbRoqLo8/fysiDMbfrC1qGt3mlYbtVkvOMCs9pxm3JTQ4DQ9gkaoVM0hS5w7ZmNhOv7Dyjf7yggEMCtZEHaqMUieVLd1MicMQl6yRH98fW3PD0+PnNybjcbTmiWlRAzqyuD47rsNCHhmXLlA=
  - secure: vK3++Ul5K5mDf8VRqIyn8yPZDJYtUUoc2FfUSeR6in/QnFHQVF8VQh4Y6EPwOuScIM95woPT9pUWDPbY5Bsl1vrmYnP7wZ6dDxvC36ni/bs8as6EZ9kDxIFPqqPmwlbUoDPTsP+KTBVdx84XfgRREiQf/A5QQ9g27n7cSTtHHIv2xej5MknkM06ud6qPSHa2zD34FhxCbINat46AOAdz0Hss+clO0TpfokuEZKfC0lzDFxpaI7kN/8w3bYVv0vGgAm1reY3kJXuCmPV7hTmS9MbQsse4GubkTUudIzYju911C/8M7mXBUFVBpL9fXY+i46EH69aSNbO7HAabI+mgIyV+VuBwB/6DuDdT+XkVbfdZ3JU4M6jqEiVIYrHjfnL6qx1I6pr/NBPMdUsOBs6lZDXP6wiRF+OQMaL8gQlMUYkmN5v1Uf5J7LY7c1JxfrLx3M//YnzpbnY9M8LpStyDyTyWoXeA3RxJrO9ysAYMePLjOX+Vg5A4jYeuFPzmLvYa3aqkG7LKTOVHPncXSwGzl+wbs8W2dGGHgLh/sDTSKqNX5G+9nZNzCyuxDbWGdos9I4iF3q+FZZmrE9eNjKIbKkbOFqL/RiOBc0kieGsCskSCTkNqMGjxIIRlw4QAI1F8M500T6ZjVkvAOBlTGTHZLkcS6xpVx8CUNA+7zk0x28A=
install:
- git clone https://github.com/flutter/flutter.git -b stable
- export PATH=$PWD/flutter/bin:$PATH
- cd ios
- bundle install
- cd ../
script:
- cd ios
- fastlane ios beta
