language: objective-c
osx_image: xcode12.2

stage:
  # - foundation
  - testflight
  # - ios
  # - android

jobs:
  include:
    - stage: testflight        # build ios and android
      name: "testfligt"
      script:
        - sudo gem install fastlane -NV
        - npm install --global yarn
        - npm install -g @ionic/cli
        - echo "foundation process done!"
        # foundation complete
        - npm --version   # display npm version to check for npx
        - yarn install    # install all dependencies
        - yarn run build
        - npx cap copy ios
        - npx cap copy android
        - echo "ios and android built!"
        # built ios and android projects
        - cd ios/App
        - sudo bundle update fastlane
        - sudo bundle install
        - bundle exec fastlane beta # deploy to testflight
        # app deployed to testflight