language: swift
osx_image: xcode12.3
env:
  global:
    secure: 6CsECfeU3yDTBQ7o4xfoF7gX4v/CinbRwn7185Mqx929ZqVIIaswhNFALxBM2OfCan+2KgXCe50yK3v27q6WsAKqEEtg9ARQCsee6NOeBZZJJGpYGhQ6Fs1eWreoI8Yh23rnnpDu+yhDKkagpKcDirlIHLZoZsnQOvKMwX6JErzIP1t3J5VnHY5MSEZhi6BE5J+jQAO458y78gqtIGnr4uKCa0C3cXDYek2VzKLd7EJIgNfmBAcnkshOZ9ETixznQipZWgg2iOwwifWBgPkeNt8sKubX5ecw8K8A0eAw6mtvAajqDXKgB/GCFBq8LLerpwmpyNZBYJSDvCtLg5s6i0KO0M8k69bbWm4MNK+Cw3cHSgCElZFZQyExbzuC/0PPFs+zBwC5yOIQowC3FDpWodmBmLtNZh/F+GUVUMERDt4BNZ/zd00HH5OxO7+hA3uTJ9ToNTdbunfARp4GcsQX6WK3fQguk4FlI3dNRkBPhZQsIPWUvHSwfxaLofNLtI+ud1bLrsnqWAhZQRjmTJjMnTflkr0sMXuA87s/4ffLXJrl9SiRqOkotwIvb63HmvWIGJgAtqSlsRdZFvDzk9a2glWJddWIPtd3H+1G+eo9GIqdmzZmBoRUt+uYDWWUq03TKykUfZ1/Vv+qYL742sSiUIZym0th7GBIc9jQcp0AWx4=
install:
- git clone https://github.com/flutter/flutter.git -b stable
- export PATH=$PWD/flutter/bin:$PATH
- cd ios
- bundle install
- cd ../
script:
- cd ios
- bundle exec fastlane beta_test
