language: swift
osx_image: xcode12.3
env:
  global:
    secure: xA6gHNcYCuxHsHqyzwO9ZCR4yys5W+qf5Oz/U8rvnWq43GIq0tM1GPwfyiGQddgLKAoGW6UnZqVEpTdQg+YT61pZFAtoqpMZl3PxSN1L6TP/QTY1RrbMOR8zdbr+5wM0PlVdaH5K5LQlTH3ZZY/vL79xfVu/GOIDMJ2Usa8zRA2PGKJaQpP4odRERuwnLgFdqKhgvCT9ihqRxCWBKV/WR8dUqKWgbDDoHWZOJWzmcZZrPv28W1dU6qLdei1TV4Ud+Thsp0ZlTUlXOD7F5MzJt8b2Kjk3RpZnN+5Z1wCMHn4BQb0Qppk0oDMSbBMI5aGhhNNzvk8ebBz+kHX8RZmIrF52XCRIkK3K+a7jeWgVMVr+2vcgsXHv2dKMuqeVZqjjoHgdJN8kvO3XKoKBkO9KUhTF2lnnVQ3TvI1MGECkBSHBtq94cDTG8Aj+X6GPzrbY2hdwBFZD4vTizXZteUoq6FmGMTtb+rwXBTiWvLABQC7fmV79oFdMw596oMADsBilD3D0T+krxN7BbW29YYHKYq6u+NSkJyhZ2yjZj4G/gl0eujq9rEvHYXWTODgsSDBZiIswiFeYFfM4RN1O4r7T4YYwCQaZpvmJgcRA6v/9oa/W+C8lMyyaW56P78WTdyu2tcQ9oCGFidNRvPVpe0anoqFwa5nOZI6aMZabYUaVZbU=
install:
- git clone https://github.com/flutter/flutter.git -b stable
- export PATH=$PWD/flutter/bin:$PATH
- cd ios
- bundle install
- cd ../
script:
- cd ios
- bundle exec fastlane beta_test
