language: swift
osx_image: xcode12.3
env:
  global:
  - secure: UJpvdecDnRrx7JsMrCf9JAmBzF6/XUxSjUkXdgsikSKx47ov/sG1n05RprURHPSwj4D2GUvzzmNUBUdoZv5bDocHgMaQ7wLGmqtp7fxYPvtMOmo2bIO730Byn3gaJvhbiGk+0DeFHdpWQMckSWoK+pp8GD2TOlgJwK8wy83I2EJkBrDEMeQIagXx6A80Ksj7GjnmPBl6t+7gPiuLSjiGR3jxc8q5Md+Y0nLZ9VWQNu2o64CD0x2uKmTd58S+qMXvQsbP52QFUUWapiT+hgvma5FC7bilq67LZsDmyhVOEq7jdLuhBvFUjnbBMSOKnJhouL1T8u1qLaL8V3PnQMWeZ47K0WVXKCGKODaSXbdc4WDFPy+JxeS9/AyLFidbppX25PQ6PkfiEuKopNRzAPKk4pTuVZiv1WX+soq/Je3sy+8it12oMqBf/lwlDE4H//+MysLnA5wSYSDm12+8kScjSmaCbttKT7S40GLWUuvfZPd6ECHr/DNo6VHkYKqoJNoMl3UBSZQhZA/ZXSlFVgVq0vlZZcA1d2ZyJdl1DPm2qpo/7InDQSuImmZJYJlLtHrrac3/QOVZvP45fwCSUJRfR+QragFnTuIewI4WqFgnQBqHR4ELs4HzsYNwCnnz01ylHOjyOsrENflZ2FQfFeXrYyBBxDn0hxrXgsBsJmnUsEM=
  - secure: cPxMEhvkjEo5oRnjw8gXwby3+27KH7nzcDzZkPgYlw76PG0kRC5dr0Iamm9g3L9jEFZio3wYkM9GamzkH3ppHUzCepKrGt2DawXql1xi0sSzeoHr07usuT5zYxk8GneCHyePbl7Bk/EY8PJ7jBu83to+CnUpZqgqxDCpa5vCO7WyRDmp6Rp898SI7moskc9k5nwkDZwYQWCqwmuJJY7oxjdmNBFPmQm+wNrVp9t3hIvCQ6TUFV0xf6WUADCcoVy45KFg8xQtNigpwF/rEbmzYe6MteJkdH2e9utK/WDbiKDWrhfOM0xSxZgAqdVvl93xOW0l4/mzPHSQvpU64AKrCbgxZPIlOj10/+WXlN3zSaQqekHuk5e+r3zWacGoTrWTYSFVOXx33TzolR+fWnTbWVms7P5TpgE0X+Ocjhs0LG/uXYeN1szchlcFw9srWUwraRJyPXLXwl0icJRPwXnYp5cIRnZa86hlO1V7MUyeNp3SVH2EbrgjEpDvMusCyi7gS5xVMaGrnLB46jprOBmc5una4ybEew/A1okbiPMH9JiDdP0zeZEqStHcbnftOSrZtMeFv9SQpGYrDNPLFK1PjagGX9hLOeH7a5977exD7fmjbOGLBvCLKUNvVymfemYvwOg2vbvRJw2E6UrW2itwtyX2GHqUg6uQPZBMQx5EcQU=
install:
- git clone https://github.com/flutter/flutter.git -b stable
- export PATH=$PWD/flutter/bin:$PATH
- cd ios
- bundle install
- cd ../
script:
- cd ios
- bundle exec fastlane beta_test
