language: swift
osx_image: xcode12.3
env:
  global:
    secure: Nhi2V0/LhuztRBV0uyfEOZ5gE5HH1mC0kdljj579Sp2LWOkAf2BjPZnoT21WlN3jGpuFn/r99bNkphvrAeyMpADH4TNjvP58MMz4GW7N2dMWkN5xFlk0QHgFV391bWAi/j7zXMv2lzuNSFUcUASU8giB4OT/L/d2NzDtz0nFm0l0Q/d6NDQEWNpJYzY5/KUWRIz2lF4Gr9UYADfWt5oOCFVFrCaKUBbbiD+XVbca28gyQn3Y258SuzyOT+WBo603vu8A6MruejinRLlHLFnT6KWRBtjuoDhQzZ6LHJpkrko28VXJ87KbkaYI0pmiWUvIZOXG1R7delhFcXTvxcudRye6OL5A2jDOcZ/K8qITcp0bzfSnifpAuDU2hhtYbuCYr/o74voW9iwRgWSRXffNgjU0QX2qP7Y0ODJQB+Oz4POK7Hti81QeA9KuVOJc+gT7p/y2JubUeIwrBe8TV6EriB5OAcf7BzTRL4rqIsPFbbMhK5k4avCrgEMQrABiiIRV6dmtq5r719esYa2NAHba7B/D4GtE1vmsllmT5Y05LQw5n8j+VRCCtJ2TqZa1PRshG5Fa+37fhmdMo6QMRk5NYfRsUa+efL1I2XhfnmvrsGDHYfOwQ+zSVV/Sh7BayD3A7jwbzg/4//zEAaAfZIxxRgWMlqoptMCgaRlO4uk6HAw=
install:
- git clone https://github.com/flutter/flutter.git -b stable
- export PATH=$PWD/flutter/bin:$PATH
- cd ios
- bundle install
- cd ../
script:
- cd ios
- fastlane ios beta_test
