language: swift
osx_image: xcode12.2
env:
  global:
  - secure: PV9MPh6n/tP8zq6rPk0r2/m33UKaybJOsHWGGnF6A79kLRrqsRFZDKCA0zDHbW9rLa26jBhreYrG0IYDqlfD7AWo4S9KgJoP28ZaPoDhSsak8+02FRa6SKloS8YhRcA0RUeSiwyk4bIdP+JaCaStnPqYdoVfzxWplrl0b2FjD76weabPjkIUcs6/SeCNZhd+/ShUNaMwQrUdY6LhfHI7QnLQ5mBBKOZKrbrbSLQ0JBkAGDmp7Cgc4WVP9dsR/4PUeUSIuPUjxeZ/ToGJhu4Sq4UnM3IpHIwEVieUPH3tAQCCVMOLDQ8TLyarjM6JIct+uql95VSHgg0sIjPI7rgpU92kZyMuftamC6tl+8eu/ZKUBPeotXrdq88yf+ETxZMZvH6X65U5dQM6jhyiPMkyiaMXahW5KrCD66CJlrFZbKtqKpsBCwHeNXk1em7OY+uoi0L6sxLzmQVvfpihVP0Is9IhnmHVFSZSIOIer0fzXqjDqdb3UcBGo3Cju+RnF1wW1ddN0gBP0I6Y+MckNEL5ClwRfw1TDWcN9tpS/wGe1LkQx0HNvhkyBgCm+mrWjOAacFD2oiZzLkk78x5apYlU935BDiXbZDdXUy+3JgMfDRIiJPKu6FF1hFSvcjb7y/qu/1uYYht9ZhljQi9f0ZJAD2nMwQBb4LQ8D3IFCsIjqt8=
  - secure: Gukxt/rrKqggnKqvNq8+jl509zU5oFkgZjDtJmg7oZAVxqXmFf5kkuh/STgWqUgcSuep/WexaWDqKMv+v737S8jPQvCgYRA2RuKeORgLWWjhEcmXHYMiRiY7KME9K8s8Ry2t6rHNXOMnUIubfdwcmajaiUmpbX/DjwOfxcZoCTv+yNxruYw/0HJD0UyoQZbshR8ejVSmFjKNbCsoloHFdG7BM4REZrPot/udX/jYoDYVjgv1M1O1IqyPmzPseRYqxZUKLvveaDLQdoDu6L907xGtu8gSo2RA2a2VnxW7jeAWLgsMDMjxfCI+3G5mGmnZM8jYHGzHpewm2BuPZKEWi/xdjd1NWsg8cWu/2XMI8c81X+O2+VQYNaucX7j74HmctSFRtf1AX/5anSvzOlQHaXZYvsriw7ji8usSIDrQB5/YFJsPa9fybgFcNh3oi7H082J9kw7aZOsEDHgGRnwDBsx7DDhILQJft9fsD5nt2BSkrh81zYrGEbXVWsQ/uDLDTu2pBQ8jJUd852LSsmGSPc5jnf2+IbgDGwNU+5CU6wyX1VCqgmEs8UxGssf97TwEUTlNgJ6QpWM8QdTmS5aq2PFmXIt+WB0lDlrWSCirAr4KxPXxwMpoB6e39m0tnJkLEb7uCv3jvswKaSb+FI0JzB0ZfckxMkuzInVUWYWkDks=
install:
- git clone https://github.com/flutter/flutter.git -b stable
- export PATH=$PWD/flutter/bin:$PATH
- cd ios
- bundle install
- cd ../
script:
- flutter build appbundle
- cd ios
- bundle exec fastlane beta
