language: swift
osx_image: xcode12.3
env:
  global:
install:
- git clone https://github.com/flutter/flutter.git -b stable
- export PATH=$PWD/flutter/bin:$PATH
- cd ios
- bundle install
- cd ../
script:
- cd ios
- bundle exec fastlane beta_test
