language: swift
osx_image: xcode12.3
env:
  global:
    secure: FN/BQ1tVxZIoYwa3AbYgTz4jFWUFgR4VCe2Xl/6YNiNXXnIDSPS3V9eME4Wj9lHorOm9qNYy480AFgofBo29STxzyJtbdVNgYWgE4twXjlXhugZJv0uXfzyUP21uHg1/oDQoQwseJ6XNgYTLrFzrwYxGDLrxOzOZ8bFggHMjE2ajzde6LsgDtQc03pT2JWNkvuXupwuEkV2q/cPCCC4MnPyj6OB6rykccv02r+bjkZcoSQ8sKsp4s/zd/t7Xo5U17/5H+onTMTBuJfcBbrS1Z5zBxPJNFYWrbakqDvkPwKZiDeWm31WicMGOR0PE5suoFCZwiYgfLmrhxLq/2wT5ugiLZWHZQ7QwveQBSXUC9TjqpRvgf3BsFQbzBcXe3I/OopyfR6CUtvBShFDraS40l536uuDXudgJxTU+AY+TmIIE+I7s9EzFwHOZGQoaJGhjJhS6IioKkIwmtPoVRG9IDVg2zQtwiXTCwuFKR1zSraR3PhrqM/+Nqf0JlGs+0N7COJrt2xUKuZBRledt++QPL+a1Bpf9A1EiQVE3BXJ39w1r6x9h6eSTMnUvSMloRCLNtlZpLGs3bD3YF0k2XeEWPAErwiJ56GLJyJj89dzReA1vw4NwjjHyWrPopRLqxTTwvpw+Fc/vWYSxO3mM0x93xEr/5vHtptrArd+mWnPDc7k=
install:
- git clone https://github.com/flutter/flutter.git -b stable
- export PATH=$PWD/flutter/bin:$PATH
- cd ios
- bundle install
- cd ../
script:
- cd ios
- fastlane ios beta_test
