# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#
# For a list of all available plugins, check out
#
#     https://docs.fastlane.tools/plugins/available-plugins
#

# Uncomment the line if you want fastlane to automatically update itself
# update_fastlane

default_platform(:ios)

platform :ios do
  desc "Push a new release build to the App Store"
  lane :release do
    match(type: "appstore", readonly: is_ci)
    build_app(scheme: "Runner")
    upload_to_app_store
  end
end

platform :ios do
  desc "Push a new beta release build to TestFlight"
  lane :beta do
    match(type: "appstore", readonly: is_ci)
    build_ios_app(scheme: "Runner", export_method: "app-store", clean: true)
    upload_to_testflight(skip_waiting_for_build_processing: true, apple_id: "1532589874")
  end
end