# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#
# For a list of all available plugins, check out
#
#     https://docs.fastlane.tools/plugins/available-plugins
#

# Uncomment the line if you want fastlane to automatically update itself
# update_fastlane

default_platform(:ios)

platform :ios do
  desc "Push a new release build to the App Store"
  lane :release do
    get_certificates
    get_provisioning_profile(force: true)
    build_app(workspace: "Runner.xcworkspace", scheme: "Runner")
    upload_to_app_store
  end
end

platform :ios do
  desc "Push a new beta release build to TestFlight"
  lane :beta do
    get_certificates # cert
    get_provisioning_profile(force: true) # sigh
    build_app(scheme: "Runner", include_bitcode: true)
    upload_to_testflight
  end
end

# same as beta but does not send to testflight
platform :ios do
  desc "Push a new beta release build to TestFlight"
  lane :beta_test do
    get_certificates(username: "starostka@pf.dk") # cert
    get_provisioning_profile(force: true) # sigh
    build_app(scheme: "Runner", include_bitcode: true)
  end
end

platform :ios do
  desc "Test ios release"
  lane :tests do
  run_tests(scheme: "Runner",devices: ["iPhone 6s", "iPad Air", "iPhone 12"])
  end
end