# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#
# For a list of all available plugins, check out
#
#     https://docs.fastlane.tools/plugins/available-plugins
#

# Uncomment the line if you want fastlane to automatically update itself
# update_fastlane
setup_travis

default_platform(:ios)

platform :ios do
  desc "Push a new beta build to TestFlight"
  lane :betaApi do
    cert
    app_store_connect_api_key(
      key_id: "C7JCWZ8MV6",
      issuer_id: "69a6de96-68a3-47e3-e053-5b8c7c11a4d1",
      key_filepath: "../../ConnectApiAuthKey.p8", # the private key is encrypted you little sneaky fella (must be placed in top-level)
      duration: 1200, # optional
      in_house: false, # optional but may be required if using match/sigh
    )
    build_app(scheme: "App", export_xcargs: "-allowProvisioningUpdates")
    pilot
  end
end

# platform :ios do
#   desc "Push a new beta release build to TestFlight (ONLY WORKS WITH PC WHERE YOU CAN LOGIN)"
#   lane :beta do
#     build_app
#     upload_to_testflight
#   end
# end
