# This is a basic workflow to help you get started with Actions

name: Fastlane Beta

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: macos-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      - name: Fastlane Action (iOS)
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: maierj/fastlane-action@v1.4.0
        with:
          lane: 'beta'
          subdirectory: 'ios'
          bundle-install-path: 'vendor/bundle'

      - name: Fastlane Action (Android)
      - uses: maierj/fastlane-action@v1.4.0
        with:
          lane: 'beta'
          subdirectory: 'android'
          bundle-install-path: 'vendor/bundle'